name: Run Python Tests

# این اکشن چه زمانی اجرا شود؟
# 1. هر بار که کدی به شاخه main پوش می‌شود.
# 2. هر بار که یک Pull Request برای شاخه main باز یا آپدیت می‌شود.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# تعریف کارها (Jobs)
jobs:
  test:
    # نام کاری که در رابط کاربری گیت‌هاب نمایش داده می‌شود
    name: Test on Python ${{ matrix.python-version }}
    
    # روی چه سیستمی اجرا شود؟ (اوبونتو یک انتخاب استاندارد و سریع است)
    runs-on: ubuntu-latest

    # استراتژی: این کار را روی چندین نسخه پایتون اجرا کن
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    # مراحل اجرای کار
    steps:
      # مرحله 1: کد پروژه را از مخزن دریافت کن
      - name: Check out repository code
        uses: actions/checkout@v4

      # مرحله 2: نسخه پایتون مورد نظر را نصب کن
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # مرحله 3: وابستگی‌های پروژه را نصب کن
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pytest را نصب می‌کنیم چون برای اجرای تست‌ها لازم است
          pip install pytest
          # برنامه خودمان و وابستگی‌هایش (Click, tqdm) را نصب می‌کنیم
          pip install .

      # مرحله 4: تست‌ها را با pytest اجرا کن
      - name: Run tests with pytest
        run: pytest